# Docker Compose config for development setup

version: '3.9'


services:

  pgdb:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  tgbot:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@pgdb:5432/${POSTGRES_DB}


volumes:
  pgdata: {}
